theme: jekyll-theme-minimal
logo: ./figures/Chris.jpeg
title: Zenan Li's homepage
description: Thanks for visiting my homepage and welcome to contact me at:<br /><br /><a href="mailto:Emiyalzn@gmail.com">📮 Emiyalzn@gmail.com</a>